name: Build and Deploy

# This workflow will run when any commit is pushed to the main branch.
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The environment to run the workflow in

    steps:
    - name: Check out latest commit
      uses: actions/checkout@v4

    - name: Set up the builder
      uses: docker/setup-buildx-action@v3

    # You need to set up permissions on your repository to allow pushing to the container registry
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io # Set this to any container registry
        username: ${{ github.repository_owner }} # Uses your GitHub username
        password: ${{ secrets.GITHUB_TOKEN }} # You need to set this in the repository

    # Set the name of the built image as an environment variable that we will later use as env.IMAGE_URL
    - name: Set the image name
      run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push the image
      uses: docker/build-push-action@v5
      with:
        context: . # The current directory
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}

    # You need to add the following secrets to your GitHub repository
    - name: Deploy image to Caprover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}:"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: "${{ env.IMAGE_URL }}"